title: Kiro Powers
description: Just a doc about kiro.dev powers
theme: just-the-docs

url: https://jpalala.github.io/kiro-powers-workshop
aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
